name: SpringBoot CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build project
        run: mvn clean package -DskipTests

      - name: Rename jar to app.jar
        run: |
          JAR=$(ls target/*.jar | head -n 1)
          echo "Jar found: $JAR"
          mv "$JAR" target/app.jar

      - name: Verify jar locally
        run: |
          ls -l target/app.jar
          file target/app.jar

      - name: Copy jar to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          source: "target/app.jar"
          target: "/opt/api-alphaqi/app.jar"
          overwrite: true

      - name: Verify jar on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "=== CHECK FILE ON SERVER ==="
            ls -l /opt/api-alphaqi
            file /opt/api-alphaqi/app.jar
            echo "==========================="

      - name: Restart service
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            systemctl stop api-alphaqi || true
            systemctl start api-alphaqi
            systemctl status api-alphaqi --no-pager
