name: SpringBoot CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # 1. Build
      - name: Build project
        run: |
          mvn clean package -DskipTests

      # 2. Kiểm tra thư mục target
      - name: Debug - list target folder
        run: |
          echo "=== LIST TARGET FOLDER ==="
          ls -l target
          echo "=========================="

      # 3. Đổi tên jar (cho chắc chắn)
      - name: Rename jar
        run: |
          mv target/*.jar target/app.jar

      # 4. Kiểm tra jar sau rename
      - name: Debug - check jar
        run: |
          echo "=== CHECK FILE ==="
          ls -l target/app.jar
          echo "=================="

      # 5. Copy jar (DEBUG MODE)
      - name: Copy jar to server (DEBUG)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          source: "target/app.jar"
          target: "/opt/api-alphaqi"
          debug: true

      # 6. Kiểm tra file trên server
      - name: Debug - check file on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "=== CHECK SERVER FOLDER ==="
            ls -l /opt/api-alphaqi
            echo "==========================="

      # 7. Restart service
      - name: Restart service
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            systemctl restart api-alphaqi
            systemctl status api-alphaqi --no-pager
